services:
  ministack:
    image: ministackorg/ministack
    container_name: eatio-ministack
    ports:
      - "4566:4566"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:7-alpine
    container_name: eatio-redis
    ports:
      - "6379:6379"

  bff:
    container_name: eatio-bff
    build:
      context: .
      dockerfile: ./apps/bff/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - ./apps/bff/.env
    depends_on:
      - ministack
      - eatio-service

  eatio-service:
    container_name: eatio-service
    build:
      context: .
      dockerfile: ./apps/eatio-service/Dockerfile
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    env_file:
      - ./apps/eatio-service/.env
    depends_on:
      - ministack